name: build
on: [workflow_call]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18.x]

        steps:
            - 
              name: checkout code
              uses: actions/checkout@v4

            - 
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - 
              name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}  
            
            - 
              name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            
            - 
              name: Cache Primes
              id: cache-primes
              uses: actions/cache@v3
              with:
                path: node-modules
                key: ${{ runner.os }}-primes

            - 
              name: Install Dependencies
              if: step.cache-primes.outputs.cache-hit != 'true'
              run: npm install
        
            - 
              name: Build and push Docker image
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                platforms: linux/amd64
                context: .  
                file: Dockerfile  
                push: true
                tags: hanum20/sshfrt:latest

